# brian's standard GitHub Actions Windows config for Perl 5 modules
# https://github.com/briandfoy/github_actions
# https://github.com/features/actions
# This file is licensed under the Artistic License 2.0
name: windows

on:
    push:
        branches:
            - '*'
        tags-ignore:
            # I tag release pushes but those should have already been tested
            - 'release-*'
        paths-ignore:
            # list all the files which are irrelevant to the tests
            # non-code, support files, docs, etc
            - '.appveyor.yml'
            - '.github/**'
            - '.gitignore'
            - '.releaserc'
            - 'Changes'
            - 'LICENSE'
            - 'README.pod'
        pull_request:

jobs:
    perl:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os:
                - windows-2019
                - windows-2016

        steps:
            - uses: actions/checkout@v2
            - name: Set up Perl
              run: |
                choco install strawberryperl
                echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
            - name: Perl version
              run: perl -V
            - name: Install
              run: cpan .
