# brian's GitHub Actions demonstrations
# Don't run this action when the branch name lists a different OS
# This means that you can target an action by branch name
#
# https://github.com/briandfoy/github_actions
# https://github.com/features/actions
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
# This file is licensed under the Artistic License 2.0
name: branches-windows

on:
    push:
# this will only run on branches starting with the string 'macos',
# and not otherwise. You can effectively turn off the action unless
# the branch name targets it.
        branches:
            - 'windows-*'
jobs:
    check:
        runs-on: macOS-latest

        steps:
            - uses: actions/checkout@v2
            - name: Platform check
              run: uname -a
            - name: Just pass
              run: true
