# brian's GitHub Actions demonstrations
# This file is licensed under the Artistic License 2.0
#
# Each step can check the commit message to see if it should run.
#
# https://github.com/briandfoy/github_actions
# https://github.com/features/actions
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
name: check-commit-message

on:
    push:
        branches:
            - '*'

# To play with this, choose which OS you want to exclude. Suppose that's
# macOS. Make a commit, put '#no-macos' somewhere (anywhere) in the commit
# message, and push. This has to be the HEAD commit, so don't make other
# commits.

jobs:
    mac-check-commit-message:
        runs-on: macos-latest
        if: "!contains(github.event.head_commit.message, '#no-macos')"
        steps:
            - name: Just pass
              run: true
    ubuntu-check-commit-message:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '#no-ubuntu')"
        steps:
            - name: Just pass
              run: true
    windows-check-commit-message:
        runs-on: windows-latest
        if: "!contains(github.event.head_commit.message, '#no-windows')"
        steps:
            - name: Just pass
              run: exit 0
