# brian's standard GitHub Actions macOS config for Perl 5 modules
# https://github.com/briandfoy/github_actions
# https://github.com/features/actions
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
# This file is licensed under the Artistic License 2.0
name: branches-macos

on:
    push:

jobs:
    mac-check:
        runs-on: macos-latest
        if: "!contains(github.event.head_commit.message, '#no-macos')"
        steps-commit-message:
            - name: Just pass
              run: true
    ubuntu-check-commit-message:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '#no-ubuntu')"
        steps:
            - name: Just pass
              run: true
    windows-check-commit-message:
        runs-on: windows-latest
        if: "!contains(github.event.head_commit.message, '#no-windows')"
        steps:
            - name: Just pass
              run: exit 0
